# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]
harray = np.array(height)
warray = np.array(weight)
# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

bmi = warray / (harray **2) * 730
print(bmi)




[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [4]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def make_matrix(low,high,shape):
   
    return np.random.uniform(low, high, shape)

make_matrix(3,14,(6,4))

array([[ 9.42876865,  6.02123337,  8.14130401,  6.78325035],
       [ 3.43717271,  7.09559215, 10.77302175,  7.36299692],
       [11.04201931,  5.84891673,  5.69946403,  9.14350141],
       [12.83090756, 10.27190847,  7.70248664, 13.0373695 ],
       [ 7.70976633,  5.78262172, 11.71440086,  4.81241993],
       [ 9.43331769,  9.74556269,  3.86129066,  6.10479416]])

### #3 - Extra: Open and load the data in for the 2021 White Sox. Create a function that takes in a category (i.e. 'H' or 'HR' or '2B') and returns the average for the team

In [5]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d = ','):
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        info = csv.reader(mData, delimiter = d)
        
        for row in info:
            data.append(row)
    return data

whitesox_data = open_csv('whitesox_2021_hitting.csv')





In [11]:

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def open_csv_as_ndarray(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names=FIELDS, dtype=DATATYPES, skip_header=1)
    return data


sox21 = open_csv_as_ndarray('whitesox_2021_hitting.csv')
# sox21

In [12]:

sox21['H']

array([ 67, 148,  45, 163, 137,  98,  93,  38,  65, 111,  52,  53,  41,
        61,  36,  40,  31,  28,  24,  17,  10,   8,   0,   2], dtype=int32)

In [18]:
def get_team_average(cat):
    return sum(sox21[cat]) / len(sox21[cat])
    

print(get_team_average('H')) # 57.0
print(get_team_average('HR')) # 7.916666666666667
print(get_team_average('2B')) # 11.416666666666666

57.0
7.916666666666667
11.416666666666666
